#!/usr/bin/env python3
"""Add the 12 `compare.*` keys to all 21 dictionaries (Task 15: comparison section).
Only inserts keys that are missing, preserving each file's existing key order,
2-space indentation and literal UTF-8 output. Run from repo root.
"""
import json
import pathlib

DICT_DIR = pathlib.Path("src/i18n/dictionaries")

# Kept deliberately short so every row label reads as a benefit claim that the
# ✓/✗ cells confirm or deny (semantics consistent across all four rows).
K = {
  "en": {
    "compare.label": "Why pay?",
    "compare.title1": "Free clones exist.",
    "compare.title2": " Here’s the difference.",
    "compare.desc": "The Play Store is full of “Dynamic Island” apps — most are ad-funded shells. Here’s how Trisle compares to a typical free clone.",
    "compare.trisle": "Trisle",
    "compare.free": "Typical free clone",
    "compare.r1": "No ads & no tracking SDKs",
    "compare.r2": "€3.99 once — never a subscription",
    "compare.r3": "True Live Activities: music, maps, calls, timers",
    "compare.r4": "Spring-physics morphs & Triple Island",
    "compare.yes": "Included with Trisle",
    "compare.no": "Not included",
  },
  "de": {
    "compare.label": "Warum bezahlen?",
    "compare.title1": "Kostenlose Klone gibt es.",
    "compare.title2": " Das hier ist der Unterschied.",
    "compare.desc": "Im Play Store gibt es viele „Dynamic Island“-Apps — die meisten sind werbefinanzierte Hüllen. So schneidet Trisle im Vergleich zu einem typischen Gratis-Klon ab.",
    "compare.trisle": "Trisle",
    "compare.free": "Typischer Gratis-Klon",
    "compare.r1": "Keine Werbung & keine Tracking-SDKs",
    "compare.r2": "5,99 € einmalig — nie ein Abo",
    "compare.r3": "Echte Live Activities: Musik, Karten, Anrufe, Timer",
    "compare.r4": "Morph-Animationen mit Federphysik & Triple Island",
    "compare.yes": "In Trisle enthalten",
    "compare.no": "Nicht enthalten",
  },
  "el": {
    "compare.label": "Γιατί να πληρώσετε;",
    "compare.title1": "Υπάρχουν δωρεάν κλώνοι.",
    "compare.title2": " Εδώ είναι η διαφορά.",
    "compare.desc": "Το Play Store γεμίζει από εφαρμογές «Dynamic Island» — οι περισσότερες είναι κελύφη που βασίζονται στη διαφήμιση. Δείτε πώς συγκρίνεται το Trisle με έναν τυπικό δωρεάν κλώνο.",
    "compare.trisle": "Trisle",
    "compare.free": "Τυπικός δωρεάν κλώνος",
    "compare.r1": "Χωρίς διαφημίσεις και SDK παρακολούθησης",
    "compare.r2": "5,99 € μία φορά — ποτέ συνδρομή",
    "compare.r3": "Πραγματικές Live Activities: μουσική, χάρτες, κλήσεις, χρονόμετρα",
    "compare.r4": "Morph με φυσική ελατηρίου & Triple Island",
    "compare.yes": "Συμπεριλαμβάνεται στο Trisle",
    "compare.no": "Δεν συμπεριλαμβάνεται",
  },
  "es": {
    "compare.label": "¿Por qué pagar?",
    "compare.title1": "Los clones gratuitos existen.",
    "compare.title2": " Esta es la diferencia.",
    "compare.desc": "La Play Store está llena de apps de «Dynamic Island» — la mayoría son cáscaras sostenidas por anuncios. Así se compara Trisle con un clon gratuito típico.",
    "compare.trisle": "Trisle",
    "compare.free": "Clon gratuito típico",
    "compare.r1": "Sin anuncios ni SDKs de rastreo",
    "compare.r2": "5,99 € una vez — nunca una suscripción",
    "compare.r3": "Live Activities reales: música, mapas, llamadas y temporizadores",
    "compare.r4": "Morphs con física de muelles y Triple Island",
    "compare.yes": "Incluido con Trisle",
    "compare.no": "No incluido",
  },
  "fr": {
    "compare.label": "Pourquoi payer ?",
    "compare.title1": "Les clones gratuits existent.",
    "compare.title2": " Voici la différence.",
    "compare.desc": "Le Play Store regorge d’applis « Dynamic Island » — la plupart sont de simples coques financées par la publicité. Voici comment Trisle se compare à un clone gratuit typique.",
    "compare.trisle": "Trisle",
    "compare.free": "Clone gratuit typique",
    "compare.r1": "Aucune pub ni SDK de pistage",
    "compare.r2": "5,99 € une fois — jamais d’abonnement",
    "compare.r3": "Vraies Live Activities : musique, cartes, appels, minuteurs",
    "compare.r4": "Morphs à physique de ressort & Triple Island",
    "compare.yes": "Inclus avec Trisle",
    "compare.no": "Non inclus",
  },
  "hi": {
    "compare.label": "क्यों भुगतान करें?",
    "compare.title1": "मुफ़्त क्लोन ज़रूर हैं।",
    "compare.title2": " पर फ़र्क यहीं है।",
    "compare.desc": "Play Store पर “Dynamic Island” ऐप्स भरे पड़े हैं — ज़्यादातर विज्ञापनों से चलने वाले खोखले ऐप हैं। देखिए Trisle आम मुफ़्त क्लोन से कैसे बेहतर है।",
    "compare.trisle": "Trisle",
    "compare.free": "आम मुफ़्त क्लोन",
    "compare.r1": "कोई विज्ञापन नहीं, कोई ट्रैकिंग SDK नहीं",
    "compare.r2": "€3.99 एक बार — कभी सब्सक्रिप्शन नहीं",
    "compare.r3": "असली Live Activities: संगीत, मैप्स, कॉल, टाइमर",
    "compare.r4": "स्प्रिंग-फ़िज़िक्स मॉर्फ़ और Triple Island",
    "compare.yes": "Trisle में शामिल",
    "compare.no": "शामिल नहीं",
  },
  "id": {
    "compare.label": "Mengapa berbayar?",
    "compare.title1": "Klon gratis memang ada.",
    "compare.title2": " Inilah bedanya.",
    "compare.desc": "Play Store penuh aplikasi “Dynamic Island” — sebagian besar hanyalah cangkang yang bertahan dari iklan. Begini perbandingan Trisle dengan klon gratis pada umumnya.",
    "compare.trisle": "Trisle",
    "compare.free": "Klon gratis pada umumnya",
    "compare.r1": "Tanpa iklan & tanpa SDK pelacakan",
    "compare.r2": "€3.99 sekali bayar — tanpa langganan",
    "compare.r3": "Live Activities sungguhan: musik, peta, panggilan, timer",
    "compare.r4": "Morph dengan fisika pegas & Triple Island",
    "compare.yes": "Termasuk di Trisle",
    "compare.no": "Tidak termasuk",
  },
  "it": {
    "compare.label": "Perché pagare?",
    "compare.title1": "I cloni gratuiti esistono.",
    "compare.title2": " Ecco la differenza.",
    "compare.desc": "Il Play Store è pieno di app «Dynamic Island» — la maggior parte sono gusci finanziati dalla pubblicità. Ecco come si confronta Trisle con un clone gratuito tipico.",
    "compare.trisle": "Trisle",
    "compare.free": "Clone gratuito tipico",
    "compare.r1": "Niente pubblicità né SDK di tracciamento",
    "compare.r2": "5,99 € una volta — mai un abbonamento",
    "compare.r3": "Live Activities vere: musica, mappe, chiamate, timer",
    "compare.r4": "Morfismi a molla e Triple Island",
    "compare.yes": "Incluso con Trisle",
    "compare.no": "Non incluso",
  },
  "ja": {
    "compare.label": "なぜ有料？",
    "compare.title1": "無料のクローンもあります。",
    "compare.title2": " 違いはここにあります。",
    "compare.desc": "Play ストアには「Dynamic Island」アプリが大量にありますが、そのほとんどは広告頼みの中身のない殻です。典型的な無料クローンと Trisle を比べてみてください。",
    "compare.trisle": "Trisle",
    "compare.free": "典型的な無料クローン",
    "compare.r1": "広告もトラッキング SDK も一切なし",
    "compare.r2": "3.99 ユーロの買い切り — サブスクなし",
    "compare.r3": "本物のライブアクティビティ：音楽・マップ・通話・タイマー",
    "compare.r4": "スプリング物理のモーフと Triple Island",
    "compare.yes": "Trisle に含まれる",
    "compare.no": "含まれない",
  },
  "ko": {
    "compare.label": "왜 유료인가요?",
    "compare.title1": "무료 클론도 있습니다.",
    "compare.title2": " 하지만 차이가 여기 있습니다.",
    "compare.desc": "Play 스토어에는 ‘다이내믹 아일랜드’ 앱이 넘쳐나지만, 대부분은 광고로 버티는 껍데기입니다. 일반적인 무료 클론과 Trisle을 비교해 보세요.",
    "compare.trisle": "Trisle",
    "compare.free": "일반적인 무료 클론",
    "compare.r1": "광고·추적 SDK 없음",
    "compare.r2": "3.99유로 일회성 — 구독 없음",
    "compare.r3": "진짜 라이브 활동: 음악, 지도, 통화, 타이머",
    "compare.r4": "스프링 물리 모프와 트리플 아일랜드",
    "compare.yes": "Trisle에 포함",
    "compare.no": "미포함",
  },
  "pt": {
    "compare.label": "Porquê pagar?",
    "compare.title1": "Os clones gratuitos existem.",
    "compare.title2": " Eis a diferença.",
    "compare.desc": "A Play Store está cheia de apps de «Dynamic Island» — a maioria são cascas sustentadas por publicidade. Veja como a Trisle se compara a um clone gratuito típico.",
    "compare.trisle": "Trisle",
    "compare.free": "Clone gratuito típico",
    "compare.r1": "Sem publicidade nem SDKs de rastreio",
    "compare.r2": "€3.99 uma vez — nunca uma subscrição",
    "compare.r3": "Live Activities reais: música, mapas, chamadas e temporizadores",
    "compare.r4": "Morphs com física de mola e Triple Island",
    "compare.yes": "Incluído na Trisle",
    "compare.no": "Não incluído",
  },
  "ru": {
    "compare.label": "Зачем платить?",
    "compare.title1": "Бесплатные клоны существуют.",
    "compare.title2": " Вот в чём разница.",
    "compare.desc": "Play Store полон приложений «Dynamic Island» — большинство из них рекламные оболочки. Вот чем Trisle отличается от типичного бесплатного клона.",
    "compare.trisle": "Trisle",
    "compare.free": "Типичный бесплатный клон",
    "compare.r1": "Без рекламы и трекинг-SDK",
    "compare.r2": "5,99 € один раз — никаких подписок",
    "compare.r3": "Настоящие Live Activities: музыка, карты, звонки, таймеры",
    "compare.r4": "Пружинные морф-анимации и Triple Island",
    "compare.yes": "Входит в Trisle",
    "compare.no": "Не входит",
  },
  "sw": {
    "compare.label": "Kwa nini ulipe?",
    "compare.title1": "Nakala za bure zipo.",
    "compare.title2": " Tofauti ni hii.",
    "compare.desc": "Play Store imejaa programu za “Dynamic Island” — nyingi ni ganda tupu linalotegemea matangazo. Hivi ndivyo Trisle inavyolinganishwa na nakala ya bure ya kawaida.",
    "compare.trisle": "Trisle",
    "compare.free": "Nakala ya bure ya kawaida",
    "compare.r1": "Hakuna matangazo wala SDK za ufuatiliaji",
    "compare.r2": "€3.99 mara moja — hakuna usajili kamwe",
    "compare.r3": "Live Activities za kweli: muziki, ramani, simu, vipima muda",
    "compare.r4": "Morph zenye fizikia ya springi na Triple Island",
    "compare.yes": "Imejumlishwa katika Trisle",
    "compare.no": "Haijajumlishwa",
  },
  "ta": {
    "compare.label": "ஏன் பணம் செலுத்த வேண்டும்?",
    "compare.title1": "இலவச குளோன்கள் உண்டு.",
    "compare.title2": " வேறுபாடு இதோ.",
    "compare.desc": "Play Store-இல் “Dynamic Island” பயன்பாடுகள் நிறைந்துள்ளன — பெரும்பாலானவை விளம்பரங்களை நம்பியுள்ள வெறும் ஓடுகள். சாதாரண இலவச குளோனுடன் Trisle ஒப்பிடும்போது எப்படி இருக்கிறது என்று பாருங்கள்.",
    "compare.trisle": "Trisle",
    "compare.free": "சாதாரண இலவச குளோன்",
    "compare.r1": "விளம்பரமில்லை, கண்காணிப்பு SDK-வும் இல்லை",
    "compare.r2": "ஒரே முறை €3.99 — சந்தா கிடையாது",
    "compare.r3": "உண்மையான Live Activities: இசை, வரைபடங்கள், அழைப்புகள், டைமர்கள்",
    "compare.r4": "ஸ்பிரிங் இயற்பியல் மார்ப்புகள் & Triple Island",
    "compare.yes": "Trisle-இல் அடங்கும்",
    "compare.no": "அடங்கவில்லை",
  },
  "th": {
    "compare.label": "ทำไมต้องจ่ายเงิน?",
    "compare.title1": "แอปเลียนแบบฟรีก็มี",
    "compare.title2": " แต่ความต่างอยู่ที่นี่",
    "compare.desc": "Play Store เต็มไปด้วยแอป “Dynamic Island” ส่วนใหญ่เป็นเพียงเปลือกที่อาศัยโฆษณา ลองเทียบ Trisle กับแอปเลียนแบบฟรีทั่วไปดู",
    "compare.trisle": "Trisle",
    "compare.free": "แอปเลียนแบบฟรีทั่วไป",
    "compare.r1": "ไม่มีโฆษณาและไม่มี SDK ติดตาม",
    "compare.r2": "จ่ายครั้งเดียว €3.99 — ไม่มีการสมัครสมาชิก",
    "compare.r3": "Live Activities แท้จริง: เพลง แผนที่ สาย ตัวจับเวลา",
    "compare.r4": "แอนิเมชันฟิสิกส์สปริงและ Triple Island",
    "compare.yes": "รวมอยู่ใน Trisle",
    "compare.no": "ไม่รวม",
  },
  "tr": {
    "compare.label": "Neden ücretli?",
    "compare.title1": "Ücretsiz klonlar var.",
    "compare.title2": " Fark işte burada.",
    "compare.desc": "Play Store, «Dynamic Island» uygulamalarıyla dolu — çoğu reklamlarla ayakta kalan boş kabuk. Trisle’nin tipik bir ücretsiz klonla farkına bakın.",
    "compare.trisle": "Trisle",
    "compare.free": "Tipik ücretsiz klon",
    "compare.r1": "Reklamsız, izleme SDK’sı yok",
    "compare.r2": "5,99 € bir kez — asla abonelik yok",
    "compare.r3": "Gerçek Canlı Etkinlikler: müzik, haritalar, aramalar, zamanlayıcı",
    "compare.r4": "Yay fiziği morphları ve Triple Island",
    "compare.yes": "Trisle’de var",
    "compare.no": "Yok",
  },
  "ur": {
    "compare.label": "ادائیگی کیوں؟",
    "compare.title1": "مفت کلون تو موجود ہیں۔",
    "compare.title2": " مگر فرق یہاں ہے۔",
    "compare.desc": "Play Store میں “Dynamic Island” ایپس کی کمی نہیں — اکثر محض اشتغالات سے چلنے والی خالی کھالیں ہوتی ہیں۔ دیکھیں Trisle ایک عام مفت کلون سے کیسے بہتر ہے۔",
    "compare.trisle": "Trisle",
    "compare.free": "عام مفت کلون",
    "compare.r1": "نہ اشتہارات، نہ ٹریکنگ SDK",
    "compare.r2": "€3.99 صرف ایک بار — کبھی سبسکرپشن نہیں",
    "compare.r3": "حقیقی Live Activities: موسیقی، نقشے، کالز، ٹائمر",
    "compare.r4": "اسپرنگ فزکس مورفز اور Triple Island",
    "compare.yes": "Trisle میں شامل ہے",
    "compare.no": "شامل نہیں",
  },
  "vi": {
    "compare.label": "Tại sao phải trả tiền?",
    "compare.title1": "Bản sao miễn phí có nhiều.",
    "compare.title2": " Khác biệt là ở đây.",
    "compare.desc": "Play Store đầy ắp ứng dụng “Dynamic Island” — phần lớn chỉ là vỏ rỗng sống nhờ quảng cáo. Hãy xem Trisle khác biệt ra sao so với một bản sao miễn phí điển hình.",
    "compare.trisle": "Trisle",
    "compare.free": "Bản sao miễn phí điển hình",
    "compare.r1": "Không quảng cáo, không SDK theo dõi",
    "compare.r2": "€3.99 một lần — không bao giờ là thuê bao",
    "compare.r3": "Live Activities thật: nhạc, bản đồ, cuộc gọi, hẹn giờ",
    "compare.r4": "Hiệu ứng morph vật lý lò xo & Triple Island",
    "compare.yes": "Đã bao gồm trong Trisle",
    "compare.no": "Không bao gồm",
  },
  "zh": {
    "compare.label": "为什么要付费？",
    "compare.title1": "免费的仿制品很多。",
    "compare.title2": " 差别在这里。",
    "compare.desc": "应用商店里不乏「灵动岛」应用，但大多数只是靠广告撑着的空壳。把 Trisle 和典型的免费仿品比一比，差别一目了然。",
    "compare.trisle": "Trisle",
    "compare.free": "典型的免费仿品",
    "compare.r1": "无广告、无追踪 SDK",
    "compare.r2": "3.99 欧元买断 — 绝无订阅",
    "compare.r3": "真正的实时活动：音乐、地图、通话、计时器",
    "compare.r4": "弹簧物理形变动画与三重岛",
    "compare.yes": "Trisle 包含",
    "compare.no": "不包含",
  },
  "bn": {
    "compare.label": "কেন অর্থ প্রদান করবেন?",
    "compare.title1": "বিনামূল্যের ক্লোন আছে।",
    "compare.title2": " পার্থক্য এখানেই।",
    "compare.desc": "Play Store-এ “Dynamic Island” অ্যাপের অভাব নেই — বেশিরভাগই বিজ্ঞাপননির্ভর ফাঁকা খোলস। সাধারণ একটি বিনামূল্যের ক্লোনের সঙ্গে Trisle কেমন, দেখুন।",
    "compare.trisle": "Trisle",
    "compare.free": "সাধারণ বিনামূল্যের ক্লোন",
    "compare.r1": "কোনো বিজ্ঞাপন বা ট্র্যাকিং SDK নেই",
    "compare.r2": "মাত্র একবার €3.99 — কখনোই সাবস্ক্রিপশন নয়",
    "compare.r3": "সত্যিকারের Live Activities: গান, ম্যাপ, কল, টাইমার",
    "compare.r4": "স্প্রিং-ফিজিক্স মর্ফ ও Triple Island",
    "compare.yes": "Trisle-এ অন্তর্ভুক্ত",
    "compare.no": "অন্তর্ভুক্ত নয়",
  },
  "ar": {
    "compare.label": "لماذا تدفع؟",
    "compare.title1": "توجد نسخ مقلّدة مجانية.",
    "compare.title2": " لكن هذا هو الفرق.",
    "compare.desc": "متجر Play مليء بتطبيقات «Dynamic Island»، معظمها أصدقة تعتمد على الإعلانات. هكذا تقارن Trisle بنسخة مجانية نموذجية.",
    "compare.trisle": "Trisle",
    "compare.free": "نسخة مجانية نموذجية",
    "compare.r1": "بلا إعلانات ولا أدوات تتبّع",
    "compare.r2": "دفعة واحدة 3.99 يورو — بلا اشتراكات",
    "compare.r3": "أنشطة حية حقيقية: الموسيقى والخرائط والمكالمات والمؤقتات",
    "compare.r4": "حركات بفيزياء النوابض وTriple Island",
    "compare.yes": "مضمّن في Trisle",
    "compare.no": "غير مضمّن",
  },
}

COMPARE_KEYS = sorted({k for loc in K.values() for k in loc if k.startswith("compare.")})
assert len(COMPARE_KEYS) == 12, COMPARE_KEYS

changed = []
for f in sorted(DICT_DIR.glob("*.json")):
    loc = f.stem
    if loc not in K:
        raise SystemExit(f"no translation set for {loc}")
    data = json.loads(f.read_text(encoding="utf-8"))
    added = 0
    for key, val in K[loc].items():
        if key not in data:
            data[key] = val
            added += 1
    if added:
        text = json.dumps(data, ensure_ascii=False, indent=2) + "\n"
        f.write_text(text, encoding="utf-8")
        changed.append(f"{loc}: +{added}")

print("\n".join(changed) if changed else "nothing to add")
